# Official Documentation
# https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/

# apiVersion: apiserver.config.k8s.io/v1
# kind: EncryptionConfiguration
# resources:
#   - resources:
#       - secrets
#       - configmaps
#     providers:
#       - aescbc:
#           keys:
#             - name: key1
#               # See the following text for more details about the secret value
#               secret: <BASE 64 ENCODED SECRET> # use the " head -c 32 /dev/urandom | base64 " command to generate the secret
#       - identity: {} # this fallback allows reading unencrypted secrets;
#                      # for example, during initial migration



## Storing the raw encryption key in the EncryptionConfig only moderately improves your security posture, compared to no encryption.
# For additional secrecy, consider using the kms provider as this relies on keys held outside your Kubernetes cluster.
# Implementations of kms can work with hardware security modules or with encryption services managed by your cloud provider.



# Use the new encryption configuration file #


# 1. Save the new encryption config file to /etc/kubernetes/enc/enc.yaml on the control-plane node.

# 2. Edit the manifest for the kube-apiserver static pod: /etc/kubernetes/manifests/kube-apiserver.yaml so that it is similar to:

# ---
# #
# # This is a fragment of a manifest for a static Pod.
# # Check whether this is correct for your cluster and for your API server.
# #
# apiVersion: v1
# kind: Pod
# metadata:
#   annotations:
#     kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.20.30.40:443
#   creationTimestamp: null
#   labels:
#     app.kubernetes.io/component: kube-apiserver
#     tier: control-plane
#   name: kube-apiserver
#   namespace: kube-system
# spec:
#   containers:
#   - command:
#     - kube-apiserver
#     ...
#     - --encryption-provider-config=/etc/kubernetes/enc/enc.yaml  # add this line
#     volumeMounts:
#     ...
#     - name: enc                           # add this line
#       mountPath: /etc/kubernetes/enc      # add this line
#       readOnly: true                      # add this line
#     ...
#   volumes:
#   ...
#   - name: enc                             # add this line
#     hostPath:                             # add this line
#       path: /etc/kubernetes/enc           # add this line
#       type: DirectoryOrCreate             # add this line
#   ...

# 3. Restart your API server.

# 4. To encrypt all secrets before the encryption, run this command to "update" all the secrets.
# this way the new encryption will take effect on all secrets pre and post encryption.
# kubectl get secrets --all-namespaces -o json | kubectl replace -f -
# 


