apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: myapp
    tier: fe

spec: #RC Spec
  template:
    metadata:
      name: test-nginx-pod
      labels:
        app: nginx
        tier: fe
    spec: # Pod Spec
      containers:
      - name: test-nginx-container
        image: nginx

  replicas: 3
  