# Exposes the service externally using a cloud provider's load balancer. 
# NodePort and ClusterIP services are automatically created, and the external load balancer will route to them.

apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  type: LoadBalancer
  ports:
    - port: 80 # Service port
      targetPort: 80 # BackEnd/Pods port
      nodePort: 30010 # node port
  selector:
     app: nginx
     tier: fe

 #--------------Essential commands--------------# 

# kubectl create service loadbalancer <svc name> --tcp=80:8080
# kubectl get service <svc name> 
# kubectl describe service <svc name> 
# kubectl delete service <svc name> 